### ISSUE TITLE
Usage with a type provider

### ISSUE THREAD

**Issue by Mateiadrielrafael** [Zaid-Ajaj/Npgsql.FSharp#37]
Can this be used with a sql type provider? If yes how?

**Comment by Zaid-Ajaj** [comment]
Hi @Mateiadrielrafael, this library can be used *alongside* a SQL type provider but does not include it  because it is simply a thin layer on top of [Npgsql](https://www.npgsql.org/) to make it work nicely from F#.  If you want static types from the query, then [FSharp.Data.Npgsql](https://github.com/demetrixbio/FSharp.Data.Npgsql) might be what you need.
