### ISSUE TITLE
NodaTime support?

### ISSUE THREAD

**Issue by ericsampson** [Zaid-Ajaj/Npgsql.FSharp#38]
Hi Zaid, how hard would it be to add NodaTime support to this library? That would be awesome. I'd be willing to try and make a PR if you could give me guidance, unless you have time yourself.
https://www.npgsql.org/doc/types/nodatime.html

All the best,
Eric

**Comment by Zaid-Ajaj** [comment]
Hello @ericsampson, it wouldn't be hard to add NodaTime support, however the current API that builds an entire table from the result set can be a little "allocatey" and the reading of rows can be sped up by caching the index of column names. I am thinking I will be implementing next major release when and include both plugins: JsonNet and NodaTime out of the box. 

I don't have a concrete time line as to when I will be working on next major release (I need to think about the soundness of the API) so in the meantime, you can just fallback to plain old Npgsql when working with NodaTime.

**Comment by ericsampson** [comment]
Thanks Zaid! If we need NodaTime before you're ready (but would still want to use the handyness of this FSharp library), would you mind if I ask some questions here if I try to implement it in our own fork and run into anything that stumps us?

One other question - do you have any examples of using Npgsql.Fsharp with table joins that you could share?

Thanks again for this wonderful library. We're just getting started with it, but it's worked out very well so far.

**Comment by Zaid-Ajaj** [comment]
> would you mind if I ask some questions here if I try to implement it in our own fork and run into anything that stumps us?

Of course! 

> do you have any examples of using Npgsql.Fsharp with table joins that you could share?

I don't at the moment, but the thing is, table joins is simply a different query, the result set is still a table that you can read the same way you do with a single table select (without joins). The difference is that you have to manually denormalize the result set if you want to create nested structures. For example if you have books table and authors table, you can easily join them but then it is up you how you create the end result whether it is authors that have books or vice-versa (many-to-many)

**Comment by Zaid-Ajaj** [comment]
Hello there @ericsampson, with the latest update as of version 3.3.0, it is possible to use plugins with this library. You will need:
 - Use an existing connection and enabling the type handlers from NodaTime on it or enabling it globally
 - Read values from `NpgsqlDataReader` like this: `Sql.execute (fun read -> read.NpgsqlReader.GetValue<Instant>(read.NpgsqlReader.GetOrdinal("timestamp")))` 
 - Provide custom parameters when needed via the `Sql.parameter` function (added in v3.3.0)

You could add a couple of extension functions to `RowReader` to make work nicely with your codebase i.e. `Sql.execute(fun read -> read.instant "timestamp")` and the same would apply by making a couple of extention functions to the `Sql` type to make it easy to add a NodaTime-specific parameter i.e. `Sql.parameters [ "timestamp", Sql.instant time ]`

With that said, I believe this issue is (finally) resolved and I will close it accordingly. Please re-open if think otherwise or have any questions :smile:

**Comment by ericsampson** [comment]
Thanks Zaid, this library keeps getting better 🤩
