### ISSUE TITLE
Use an existing connection

### ISSUE THREAD

**Issue by ianrussellsoftwarepark** [Zaid-Ajaj/Npgsql.FSharp#47]
Hi Zaid,

Rather than creating a new connection, could I pass in an existing connection? We use scoped connections in Giraffe/ASPNETCORE.  

Regards,
Ian

**Comment by Zaid-Ajaj** [comment]
Hello @ianrussellsoftwarepark, this is an interesting take. As of now, it is not possible to use an existing connection because I tried as much as I can to hide connection management details away from the users: connections are spun up, used and disposed of internally. 

However, it is definitely possible to add such a feature. I am thinking the API would have a function called `Sql.useExistingConnection` that is called before providing the query:
```fs
Sql.useExistingConnection scopedConnection
|> Sql.query "SELECT * FROM table"
// etc
```
This means that the [SqlProps](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/src/Sql.fs#L89) type would need to have another field `ExistingConnection : NpgsqlConnection option` and if that field has a value then the library shouldn't dispose of the connection, correct? 

I open to adding this feature. However, I can't say when I will be able to add it. However, if you are willing to send a PR with the feature & tests, I will gladly review and merge ASAP :smile:

**Comment by ianrussellsoftwarepark** [comment]
I'm pleased you're open to the suggestion. :)

We wouldn't want it to dispose of the connection.  

I'll have a look at the weekend and see if I can do it!

**Comment by Zaid-Ajaj** [comment]
Looking forward to it :smile:

**Comment by Zaid-Ajaj** [comment]
Hello Ian, sorry about this but I want to ask you to postpone the work on this feature for a bit. I've started working on the library for the next version to optimize performance and provide better support for the types of postgres. I will probably end up with breaking changes so I would like to ask you to wait for the next major version (will be available soon) before making any big changes to the library :pray:

**Comment by ianrussellsoftwarepark** [comment]
No problem. :)

**Comment by Zaid-Ajaj** [comment]
Hello Ian, sorry to keep you waiting, I have published the next major version of this library as of v2.0.0 and now the library is a lot more focused, faster and exact. You can on the issue when you have time for it

**Comment by aaronmu** [comment]
@ianrussellsoftwarepark, @Zaid-Ajaj, using an existing connection would be a nice addition. Slightly related, it would also be cool to be able to use an existing transaction. Being able to compose transactions inside of a connection would be really nice! I always fall back to bare Npgsql whenever I need to do this.

**Comment by Zaid-Ajaj** [comment]
Hello @ianrussellsoftwarepark, 

I was wondering if you are still planning on implementing the feature. Please let me know if you are and whether you need help in doing so :wink:

**Comment by ianrussellsoftwarepark** [comment]
@Zaid-Ajaj I would like to do it but am struggling with time at the moment. I'm happy for someone else to do it if they have a more urgent need than me.

**Comment by Zaid-Ajaj** [comment]
Added as of #53
