### ISSUE TITLE
Is v3 missing the executeScalar variants?

### ISSUE THREAD

**Issue by njlr** [Zaid-Ajaj/Npgsql.FSharp#50]
It would be nice to have an execute variant that expects a single row. Common use-case is inserting a row and returning an id. 

```fsharp
let createUserAccount username passwordHash db : Async<Result<Guid, Exception>> = 
    let sql =
      """
        INSERT INTO user_accounts
          (
            username,
            password_hash
          )
        VALUES
          (
            @username,
            @password_hash
          )
        RETURNING id
      """

    db
    |> Sql.query sql
    |> Sql.parameters
      [
        "username", Sql.string username
        "password_hash", Sql.string passwordHash
      ]
    |> Sql.executeScalarAsync (fun reader -> reader.uuid "id")
```

**Comment by Zaid-Ajaj** [comment]
> Is v3 missing the executeScalar variants?

Yes it is. They were removed because they made assumptions about the number of rows returned by the result set. I realized that it is much easier to just use `Sql.execute` for single rows for a uniform handling of result sets:
```fs
let createUserAccount username passwordHash db : Async<Result<Guid, Exception>> = 
    db
    |> Sql.query insertQuery
    |> Sql.parameters [ "username", Sql.string username ]
    |> Sql.executeAsync (fun reader -> reader.uuid "id")
    |> Async.map (function 
         | Ok [ id ] -> Ok id 
         | Ok _ -> failwith "Expected one row" 
         | Error error -> Error error)         
``` 
Of course, you could easily write `Sql.executeScalar` if you need it
```fs
module Sql = 
  let executeScalar (read: RowReader -> 't) (props: SqlProps) : Result<'t, exn> =
    match Sql.execute read props with 
    | Ok [ row ] -> Ok row
    | Ok rows -> Error (System.Exception(sprintf "Expected one row, result set had %d rows." (List.length rows)))
    | Error error -> Error error 
```
Same idea goes for `Sql.executeScalarAsync`. I think I want to keep the base library as simple as possible and only relying on `Sql.execute` and `Sql.executeAsync`

**Comment by njlr** [comment]
I don't think it makes an assumption, it's more like an assertion: if I don't get back exactly one row then throw an error. 

My work-around is a bit like yours: 

```fsharp
let createUserAccount username passwordHash db : Async<Result<Guid, Exception>> = 
    let sql =
      """
        INSERT INTO user_accounts
          (
            username,
            password_hash
          )
        VALUES
          (
            @username,
            @password_hash
          )
        RETURNING id
      """

    db
    |> Sql.query sql
    |> Sql.parameters
      [
        "username", Sql.string username
        "password_hash", Sql.string passwordHash
      ]
    |> Sql.executeScalarAsync (fun reader -> reader.uuid "id")
    |> Async.map (Result.bind (fun x -> try Ok (Seq.exactlyOne x) with exn -> Error exn))
```

The difference being that if multiple records are returned then it gives `Result.Error`.

**Comment by Zaid-Ajaj** [comment]
Your workaround is something that can be easily added to application without any effort and you can choose here what kind of error to throw if you get more than one row. The nice thing about using just `Sql.execute` is that you can return a single *row* instead of a value like `executeScalar` did in the previous versions:
```fs
Sql.execute (fun read -> read.uuid "id", read.text "username", read.bit "email_confirmed") 
```
I will your workaround to the documentation but I don't think I will be adding to the core library because like I mentioned before: I don't want to make assumptions about the number of rows in the result set and I want to keep the library as simple as possible (unless a lot of people complain about not having such helper in the library)

Another reason for just using `Sql.execute` is because it is compatible with [Npgsql.FSharp.Analyzer](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer)

**Comment by njlr** [comment]
OK makes sense, happy to close for now.
