### ISSUE TITLE
Allow running arbitrary async code in a transaction?

### ISSUE THREAD

**Issue by lydell** [Zaid-Ajaj/Npgsql.FSharp#54]
Hi! Thanks for creating this library! It has been very nice to use.

At work we have this use case:

1. Start transaction
2. `UPDATE scheduler.schedule SET sent_date = @now WHERE id = @id`
3. Publish a message to RabbitMQ (quick async operation that can fail)
4. Commit transaction, or rollback if publishing to RabbitMQ failed

We couldn’t find a way to do this, so we rolled our own. Since we’re not super experienced F#/dotnet developers, we simply copied `executeTransactionAsync` and modified it slightly to do what we needed. Here’s the result:

```fs
type QueryOrAsync =
    | SqlQuery of string * List<List<string * SqlValue>>
    | CustomAsync of Async<Result<unit, string>>

// Based on: https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/dad861b4f2e5a27300747854052bd033a2438bf3/src/Sql.fs#L554-L589
// Changed `(props: SqlProps)` to `(connectionString: string)` as a workaround for `SqlProps` being kinda private.
let executeTransactionAsyncWithCustomAsyncs (queries: List<QueryOrAsync>) (connectionString: string) =
    async {
        try
            let! token = Async.CancellationToken
            // Changed `props.CancellationToken` to `CancellationToken.None` because private.
            use mergedTokenSource = CancellationTokenSource.CreateLinkedTokenSource(token, CancellationToken.None)
            let mergedToken = mergedTokenSource.Token
            if List.isEmpty queries then
                return Ok []
            else
                // Changed from `getConnection props` because private.
                let connection = new NpgsqlConnection(connectionString)
                try
                    // Removed `if x then connection.Open()` because we got "Connection already open" errors otherwise.
                    // Doesn’t make sense to first open synchronously and then asynchronously on the next line?
                    do! Async.AwaitTask(connection.OpenAsync mergedToken)
                    use transaction = connection.BeginTransaction()
                    let affectedRowsByQuery = ResizeArray<int>()
                    for queryOrAsync in queries do
                        match queryOrAsync with
                        | SqlQuery(query, parameterSets) ->
                            if List.isEmpty parameterSets then
                                use command = new NpgsqlCommand(query, connection, transaction)
                                let! affectedRows = Async.AwaitTask(command.ExecuteNonQueryAsync mergedToken)
                                affectedRowsByQuery.Add affectedRows
                            else
                                for parameterSet in parameterSets do
                                    use command = new NpgsqlCommand(query, connection, transaction)
                                    // We had to copy the entire `populateRow` function into our code
                                    // since `poulateRow` is private...
                                    populateRow command parameterSet
                                    let! affectedRows = Async.AwaitTask(command.ExecuteNonQueryAsync mergedToken)
                                    affectedRowsByQuery.Add affectedRows
                        | CustomAsync asyncResult ->
                            // Please excuse our ugly async code.
                            let theAsync =
                                async.Bind
                                    (asyncResult,
                                     function
                                     | Ok() -> async.Return()
                                     | Error message -> raise (System.Exception(message)))
                            do! theAsync
                    do! Async.AwaitTask(transaction.CommitAsync mergedToken)
                    return Ok(List.ofSeq affectedRowsByQuery)
                finally
                    connection.Dispose()
        with error -> return Error error
    }
```

The above allows us to do the following:

```
sendEvent now publishScheduledEvent connectionString eventToTrigger =
    connectionString
    |> executeTransactionAsyncWithCustomAsyncs
        [ SqlQuery
            ("UPDATE scheduler.schedule SET sent_date = @now WHERE id = @id",
                [ [ ("now", Sql.timestamptz now)
                    ("id", Sql.int64 eventToTrigger.id) ] ])
            CustomAsync(publishScheduledEvent eventToTrigger.payload) ]
```

We’ve tried it and it works: If `publishScheduledEvent` fails, the `scheduler.schedule` table isn’t updated.

Would you be interested in adding something like this to your library? You might be able to come up with a much nicer API than we did (we didn’t spend much time on it). As long as we can fulfil our use case we’d be happy!

**Comment by Zaid-Ajaj** [comment]
Hello Simon! This is indeed a very interesting use-case for the library and you did the right choice by implementing it yourself. The code doesn't look bad at all and it serves the purpose, so all good. As for the question of adding it to the library, I am afraid that isn't a good idea. This use case is very extremely specific because it couples the properties of a transaction with the success of another entirely different arbitrary operation. I would like to keep the library as small as possible and as focused as possible on the SQL aspects of things. 

The general recommendation is that if you need anything that falls outside the scope of the library, fallback to the `Npgsql` API which is also not so bad to work with in the first place. You seem to have done that successfully with the help of a couple of helper functions from this library.

**Comment by lydell** [comment]
Hi! Thanks for the reply!

I have a couple of questions:

1. I’m no backend expert, but isn’t it kind of standard that database libs provide a way to couple properties of a transaction with the success of another entirely different arbitrary operation? For example, [Django transactions](https://docs.djangoproject.com/en/3.0/topics/db/transactions/#controlling-transactions-explicitly) And this is not specific at all – it is instead super general? @ericsampson Since you :+1:-ed this issue, what’s your use case?

2. Implementing this ourselves was _not_ easy and felt like a giant hack. As mentioned in the code, we had to drop lots of Npqsql.Fsharp features (that we luckily don’t use (yet?)) since we couldn’t access private parts of Npgsql.Fsharp. Also, we had to copy this entire thing into our code, which did not feel good:

   ```fs
   // Copied from: https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/dad861b4f2e5a27300747854052bd033a2438bf3/src/Sql.fs#L483-L515
   let private populateRow (cmd: NpgsqlCommand) (row: (string * SqlValue) list) =
       for (paramName, value) in row do
           let paramValue, paramType: obj * NpgsqlTypes.NpgsqlDbType option =
               match value with
               | SqlValue.Bit value -> upcast value, Some NpgsqlTypes.NpgsqlDbType.Bit
               | SqlValue.String text -> upcast text, Some NpgsqlTypes.NpgsqlDbType.Text
               | SqlValue.Int i -> upcast i, Some NpgsqlTypes.NpgsqlDbType.Integer
               | SqlValue.Uuid x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.Uuid
               | SqlValue.Short x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.Smallint
               | SqlValue.Date date -> upcast date, Some NpgsqlTypes.NpgsqlDbType.Date
               | SqlValue.Timestamp x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.Timestamp
               | SqlValue.TimestampWithTimeZone x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.TimestampTz
               | SqlValue.Number n -> upcast n, Some NpgsqlTypes.NpgsqlDbType.Double
               | SqlValue.Bool b -> upcast b, Some NpgsqlTypes.NpgsqlDbType.Boolean
               | SqlValue.Decimal x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.Money
               | SqlValue.Long x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.Bigint
               | SqlValue.Bytea x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.Bytea
               | SqlValue.TimeWithTimeZone x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.TimeTz
               | SqlValue.Null -> upcast System.DBNull.Value, None
               | SqlValue.TinyInt x -> upcast x, None
               | SqlValue.Jsonb x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.Jsonb
               | SqlValue.Time x -> upcast x, Some NpgsqlTypes.NpgsqlDbType.Time
               | SqlValue.StringArray x -> upcast x, Some(NpgsqlTypes.NpgsqlDbType.Array ||| NpgsqlTypes.NpgsqlDbType.Text)
               | SqlValue.IntArray x -> upcast x, Some(NpgsqlTypes.NpgsqlDbType.Array ||| NpgsqlTypes.NpgsqlDbType.Integer)
   
           let paramName =
               if not (paramName.StartsWith "@") then sprintf "@%s" paramName else paramName
   
           match paramType with
           | Some x -> cmd.Parameters.AddWithValue(paramName, x, paramValue) |> ignore
           | None -> cmd.Parameters.AddWithValue(paramName, paramValue) |> ignore
   ```

3. I hoped that this part would catch your attention:

   ```fs
   // Removed `if x then connection.Open()` because we got "Connection already open" errors otherwise.
   // Doesn’t make sense to first open synchronously and then asynchronously on the next line?
   do! Async.AwaitTask(connection.OpenAsync mergedToken)
   ```

   Remember that our code is originally copy-paste of `executeTransactionAsync`. When we finally understood why our code kept failing with "Connection already open" it left us thinking – does `executeTransactionAsync` work at all? If so, how?

I’ll try and rewrite our SQL+RabbitMQ code as pure Npgsql and see what that looks like now, but I still think this functionality could belong to Npgsql.Fsharp. The choice is yours of course!

**Comment by lydell** [comment]
When being used to the ultra-clean usage of Npgqsql.FSharp, this looks incredibly messy:

```fsharp
// Based on: https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/dad861b4f2e5a27300747854052bd033a2438bf3/src/Sql.fs#L554-L589
// Feature request for being able to do this with Npqsql.FSharp: https://github.com/Zaid-Ajaj/Npgsql.FSharp/issues/54
let sendEvent now publishScheduledEvent connectionString eventToTrigger =
    async {
        try
            let! token = Async.CancellationToken
            let connection = new NpgsqlConnection(connectionString)
            try
                do! Async.AwaitTask(connection.OpenAsync token)
                use transaction = connection.BeginTransaction()
                use command =
                    new NpgsqlCommand("UPDATE scheduler.schedule SET sent_date = @now WHERE id = @id", connection,
                                        transaction)
                command.Parameters.AddWithValue("@now", NpgsqlTypes.NpgsqlDbType.TimeTz, now) |> ignore
                command.Parameters.AddWithValue("@id", NpgsqlTypes.NpgsqlDbType.Bigint, eventToTrigger.id) |> ignore
                let! affectedRows = Async.AwaitTask(command.ExecuteNonQueryAsync token)
                if affectedRows <> 1 then
                    raise (System.Exception(sprintf "Expected 1 changed row, but got: %A" affectedRows))
                do! publishScheduledEvent eventToTrigger.payload
                    |> Async.bind (function
                        | Ok() -> Async.singleton()
                        | Error message -> raise (System.Exception(message)))
                do! Async.AwaitTask(transaction.CommitAsync token)
                return Ok()
            finally
                connection.Dispose()
        with error -> return Error(error.ToString())
    }
```

**Comment by lydell** [comment]
Another idea: Expose more of the library to make it easier to extend.

**Comment by ericsampson** [comment]
@lydell I don't have a usecase at the moment, but it does feel like functionality that would be useful for people who do need it. I can understand not wanting to make the base library too complicated, so maybe adding extension points is a good compromise...

**Comment by richardcrichardc** [comment]
I have just hit a need for arbitrary transactions. 

1. Insert a new record - primary key is postgres serial.
2. Get back newly generated primary key.
3. Insert a bunch of associated records that reference the new record above into another table.
   
This strikes me as a pretty common use-case, which makes me thing I might have missed something obvious.

If I was inserting just one record dependent on the initial insert I could do the initial insert in a WITH, but it's a one to many relationship, so number of subsequent inserts are variable.

**Comment by aspnetde** [comment]
@lydell Recommended read: [Transactionally Staged Job Drains in Postgres](https://brandur.org/job-drain)

**Comment by richardcrichardc** [comment]
For the general case a function with this signature (for the synchronous case) could be useful:

    executeInTransaction: 
       work: (SqlProps -> bool ) ->
       props  : SqlProps ->
             -> Option<exn>

Instead of passing queries to the transaction function, you pass a function which runs the queries, using the existing API methods along with any other arbitrary code that needs to be in the scope for the database transaction. The user function can then return true or false to determine whether the transaction is committed or rolled back.

**Comment by jukkhop** [comment]
Also having an immediate use case for this, +1 from me.

`executeInTransaction` should take a function of type `NpgsqlTransaction -> 'a` as its only argument, returning whatever the callback returns. The existing `execute` and `executeRow` functions (and what-have-you) should have variants which take a transaction as argument and run the command inside the transaction. Before returning, `executeInTransaction` should commit the transaction.

In code, this would look something like this:

```
let createdBankTransfer = Sql.inTransaction (fun tx ->
  let balance = Sql.query tx "select balance from account where id = 1" (fun read -> read.int64 "balance")
  if balance >= 100 then
    Sql.nonQuery tx "update account set balance = balance - 100 where id = 1"
    Sql.nonQuery tx "update account set balance = balance + 100 where id = 2"
    { TransferId = 1; FromAccountId = 1; ToAccountId = 2; TransferAmount = 100 }
)
```

This is a crude example and wrong by-design but it should get the point across, and I think this programming model would be suitable for a lot of use cases.

**Comment by absolutejam** [comment]
I like @jukkhop's suggestion, and I think a continuation-style approach makes sense. It's reminiscent of Elixir's `Ecto.Multi.run`.

**Comment by Zaid-Ajaj** [comment]
Alright, so it took awhile for me to come up with a serious API to tackle this problem that I am actually happy with. Although I liked the continuation style by @jukkhop, it meant that the library has to have specific transaction command and non-transaction commands. 

Instead, I came up with the following API as of v3.12 (please see new docs) which allows to run the SQL commands or any arbitrary code in the context of a transaction. You basically create the transaction yourself and _re-use_ it across commands as follows:
```fs
open Ngpsql
open Npgsql.FSharp

let connectionString = " . . . "

// 1) Create the connection
use connection = new NpgsqlConnection(connectionString)
connection.Open()

// 2) Create the transaction from the connection
use transaction = connection.BeginTransaction()

// 3) run SQL commands against the transaction
for number in [1 .. 10] do
    let result =
        Sql.transaction transaction
        |> Sql.query "INSERT INTO table (columnName) VALUES (@value)"
        |> Sql.parameters [ "@value", Sql.int 42 ]
        |> Sql.executeNonQuery

    printfn "%A" result

// 4) commit the transaction, rollback or do whatever you want
transaction.Commit()
```
The magic happens when you provide the transaction via the `Sql.transaction` function.

If you don't like creating the connection yourself because you want to use the builder API, you can instead let the library create the connection as follows:
```fs
use connection =
    connectionString
    |> Sql.connect
    |> Sql.createConnection

connection.Open()
```
Please give this a try and let me know if you encounter any problem

**Comment by witoldsz** [comment]
I have just found out the new thing with transactions. I am wondering if it was already possible before:
- create the connection yourself
- begin transaction on it
- pass that connection everywhere (instead of connection string), use `Sql.existingConnection`
- when you're done, commit/rollback the transaction created above

Isn't it exactly the same, I mean the `Sql.transaction` would just get the transaction's connection, and then follow same path as `Sql.existingConnection`?

**Comment by Zaid-Ajaj** [comment]
> I mean the Sql.transaction would just get the transaction's connection, and then follow same path as Sql.existingConnection?

It is not entirely the same because in my understanding, sharing the same connection to execute the SQL commands is not the same as sharing the same transaction to run the SQL commands against.  (Please correct me if I am wrong here)

The _commands_ that you execute when starting with `Sql.transaction` are [derived from the input transaction](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/src/Npgsql.FSharp.Tasks.fs#L202) rather than directly from the input existing connection which solves the issue that @lydell had in the beginning: having to use the lower-level API rather than keeping the same patterns with the `Sql` builder API

**Comment by witoldsz** [comment]
Well, I am not 100% sure in .Net, but I am 100% sure how it works in Java (JDBC). When you get a connection and run a transaction – it's tied to that very connection. One cannot have different distinct transactions or a transaction and not-a-transaction within single connection.

I would be very surprised if that worked differently in .Net, because this is how Postgres works:
- get a connection (from pool or open new one)
- send BEGIN TRANSACTION over the wire
- the connection is now performing operations withing that transaction

So, when I saw the new release of this library, supporting `NpgsqlTransaction` explicitly – I did rewrite all my SQL code to use it. I was passing `NpgsqlConnection` with open transaction previously though. I had no chance to see how it worked, because my app is still a proof-of-concept and it's not runnable yet.

**Comment by Zaid-Ajaj** [comment]
@witoldsz there is an easy to find out, just adding a new test like [this one](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/tests/NpgsqlFSharpTasksTests.fs#L165) but instead with an open connection shared across the commands. 

It could be the case that an explicit `NpgsqlTransaction` is not needed for a simple "all-or-nothing" approach but I believe it allows for more fine grained control over the transaction because you can have "named save points" that you can roll back to which I don't think are available for an `NpgsqlConnection` instance.

**Comment by witoldsz** [comment]
> I believe it allows for more fine grained control over the transaction because you can have "named save points" that you can roll back to which I don't think are available for an NpgsqlConnection instance.

I believe there is no difference if one passes `NpgsqlConnection` or `NpgsqlTransaction` to this library functions. If the connection and transaction objects are bound, one can still do whatever they find useful with transaction object anyway (like save points).

**Comment by Zaid-Ajaj** [comment]
@witoldsz I think there are cases where you want an explicit transaction instead of sharing the connection and that is when you are using _scoped connections_: there are connections that are can be reused in a single request across the services that run during that single request. In those cases, you don't want to open a shared transaction from the connection that is potentially being used somewhere else. 

Anyways, it could be that in your case you only need a single shared connection. From the library perspective, however,  I am only providing a thin layer on top what is possible by `Npgsql` and you can keep using the API the same way it was before.

**Comment by witoldsz** [comment]
I have already changed my app to use `NpgsqlTransaction`. I am not an expert in .Net database drivers, for me it looks like (kid of) _syntactic sugar_ and I am fine with it. Maybe you are right, but from what I can see (by quick browsing the API) the transaction and connection are bound and if there are some kind of _channels_ derived from a single connection (?) – that's fine.

**Comment by Zaid-Ajaj** [comment]
>  for me it looks like (kid of) syntactic sugar and I am fine with it. 

That's literally the point of this library: thin F# layer on top of the main Npgsql library and the simple API made it possible to build the [static SQL analyzer](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer) which is another reason why I keep the surface API to a minimum

**Comment by witoldsz** [comment]
> which is another reason why I keep the surface API to a minimum

All I wanted to say is that _probably_ the extension you have added to the API (making the API itself bigger, not smaller) was not necessary to handle the OP case. All they had to do to solve their issue was to get the connection, begin the transaction and pass that bound connection to the API functions, using `Sql.existingConnection` as it was before v3.12.

On Stack Overflow there is a question: [PostgreSQL multiple transactions on the same connection](https://stackoverflow.com/questions/11620263/postgresql-multiple-transactions-on-the-same-connection) and the answer is clear: single connection is bound to the single transaction, if any. This is how it works in JDBC as well.

Please, do not get me wrong. I am not arguing about this feature in 3.12, it's not bad, it just seems a little bit redundant – thought you may find it useful, I am fine with it.

**Comment by richardcrichardc** [comment]
I have not had a chance to try it yet @Zaid-Ajaj, but thanks for adding this feature. It will be good to have a straightforward well-documented way to run SQL in transactions with the ability to COMMIT or ROLLBACK as required.

**Comment by Zaid-Ajaj** [comment]
I'll assume this is resolved in latest, reopen the issue if the problem persists ;)

**Comment by lydell** [comment]
This is on my list of stuff to try out – I’ll let you know once I get to it! :+1:
