### ISSUE TITLE
Sql.execute skip or return error 

### ISSUE THREAD

**Issue by codingedgar** [Zaid-Ajaj/Npgsql.FSharp#61]
Currently execute read signature is `read : RowReader -> 't`, how to handle this:

```fs
    |> Sql.execute (fun read ->
        {
            Id = read.int "user_id"
            FirstName = read.text "first_name"
            ComplexField = toComplexField (read.text "last_name") // <-- what if toComplexField returns an Option/Either/Throw (a parse error)?
        })
 ```

Is there a way to skip a column? or this kind of cases should be handled outside the read function?

**Comment by Zaid-Ajaj** [comment]
Hi @codingedgar, I believe you can use `Sql.iter (read: RowReader -> unit)` which allows you to control what you want to do with the `RowReader`, commonly adding relevant rows into some `ResizeArray<YourType>`.

That said, you can always make the decisions in the `read` function and return `Option<'u>` instead of just `'t` and then filtering our those values that didn't match your criteria

**Comment by codingedgar** [comment]
Thank you so much for the quick response, `Sql.iter` is not documented I think? or at least I cannot find it in the README.md, both options are great! thank you 💛

**Comment by Zaid-Ajaj** [comment]
> Sql.iter is not documented I think?

It is not documented indeed, do I feel a PR coming through? :wink: 

Anyways, glad one of options solves your problem :smile:
