### ISSUE TITLE
Allow returning a Task from the reader

### ISSUE THREAD

**Issue by pbiggar** [Zaid-Ajaj/Npgsql.FSharp#93]
I have a lot of code that looks like this:

```
type T = { x : string }
let do_some_query () : Task<List<T>>
  Sql.query "select x from ..."
  |> Sql.parameters [...]
  |> Sql.executeAsync (fun read -> { x = read.string "x" })
```

Obviously this is a cut down example.

I now need to call another async function to fill one of the fields of the records. AFAICT there isn't a function which allows the reader function to return a task and do an implicit `bind`. As a result, my code looks like this

```
let do_some_query () : Task<List<T>>
  Sql.query "select x from ..."
  |> Sql.parameters [...]
  |> Sql.executeAsync (fun read -> read.string "x")
  |> Task.bind (fun list ->
         List.map list (fun x ->
                          task { 
                            let! x = myAsyncFunc x
                            return { x = x }
                          })
         |> Task.flatten)
```

I would much rather write:

```
let do_some_query () : Task<List<T>>
  Sql.query "select x from ..."
  |> Sql.parameters [...]
  |> Sql.executeBindAsync (fun read -> 
       task { 
          let! x = read.string "x" |> myAsyncFunc
          return { x = x })
```

Have you considered adding a set of functions where the reader returns a Task?

**Comment by Zaid-Ajaj** [comment]
Hi there @pbiggar, this is an interesting use case. I would probably call it `executeEachRowAsync` but can you tell me more about the use case? I don't see it used as often because if you had to run a task for each row, there might be some unwanted overhead (especially when not running the tasks in parallel). Here is how you run the tasks in parallel outside of the reader:

```fs
let do_some_query() = 
    task {
        let! rows = 
            Sql.query "select x from ..."
            |> Sql.parameters [...]
            |> Sql.executeAsync (fun read -> read.string "x")

        let tasks = seq { for row in rows do yield myAsyncFunc row }
        return! Tasks.WhenAll tasks
    }
```
where `myAsyncFunc` would do the async work, modify `row` and return a new one. Then `Tasks.WhenAll` will run each task in parallel and combine the results into one (I guess like `Task.flatten`). 

Isn't this a better approach than running each async task in sequence for each reader row?

**Comment by pbiggar** [comment]
The use case was just to have the code be a little bit nicer by removing boilerplate. I think you have a good point with the parallelism (not relevant in my case), but that makes it a lot less useful in the general case.

Reading between the lines, I think you might also be pointing out that doing task-related stuff inline would hold open DB server resources - is that correct? If so, probably a very bad idea.

Either way, I think it better to stick to what's here. Thanks for looking at this!
