### ISSUE TITLE
Using connection string twice in Async hangs forever

### ISSUE THREAD

**Issue by AlexeyRaga** [Zaid-Ajaj/Npgsql.FSharp#95]
Invocation hangs when the same connection string is used twice in the `async` block

This example demonstrates the problem:

```fsharp
let run =
    async {
        let c1 = connectionString |> Sql.connect
        let! res = c1 |> Sql.query "SELECT 1" |> Sql.executeNonQueryAsync |> Async.AwaitTask

        let c2 = connectionString |> Sql.connect

        return res
    } |> Async.RunSynchronously
```

It hangs when trying to `connect` second time on this line: `let c2 = connectionString |> Sql.connect`.

Expected behaviour: the function does not hang ;)

**Comment by Zaid-Ajaj** [comment]
Hi @AlexeyRaga, this looks a bit weird because [Sql.connect](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/src/Npgsql.FSharp.fs#L79-L82) doesn't _actually_ open any connection until you run `Sql.execute*`

I think it is more likely that the first invocation is hanging because it cannot open and no timeout is configured in the connection string.

**Comment by AlexeyRaga** [comment]
I figured one thing: because my `run` was a _value_ and not a _function_ it behaves this badly.

But if I change it into a function like:

```fsharp
let run () = ... //same code

[<EntryPoint>]
let main _ =
  run ()
  0
```

then it all works!

I guess it is some strictness that messes stuff up here... Perhaps I am too mush used to Haskell :)
