### ISSUE TITLE
Best approach to update sql table with many optional fields with different types?

### ISSUE THREAD

**Issue by lanyusan** [Zaid-Ajaj/Npgsql.FSharp#98]
I am trying out this lib on a project with Giraffe.

One use case is that a web app needs to submit an update request with a dozen fields that are mostly optional. The request comes in in JSON through JS fetch. The REST api handler will bind the payload to a record with optional fields defined as `int option` or `string option`. If a field comes in as `None`, then the update sql should skip the field.

Is there a recommended approach to model the request payload and build up the update sql in a unified way?

It is easy with dynamical  language such as js or Clojure. But I am not sure if there is a good way with F#. 

Thanks in advance and my apology if it is a naive question. I did a search but couldn't find out good answers.

**Comment by Zaid-Ajaj** [comment]
Hi there @lanyusan, 

Do you have a specific example I can help you with?

I think what you want is kind of "update property if provided or keep it as is otherwise", right?

Let's assume you have a table called `todos` where you have this record that maps to the table
```fs
type Todo = { 
  Id: int64
  Name: string
  Completed: bool 
} 
```
And have this model for updating the todo where you bind the input JSON into this:
```fs
type UpdateTodo = { 
  Id: int64
  Name: string option
  Completed: bool option
} 
```
Update the todo as follows:
```fs
let updateTodo (existingTodo: Todo) (updateModel: UpdateTodo) = 
  connectionString
  |> Sql.connect
  |> Sql.query "UPDATE todos SET name = @name, completed = @completed WHERE todo_id = @id"
  |> Sql.parameters [ 
            "@name", Sql.text(defaultArg existingTodo.Name updateModel.Name)
            "@completed", Sql.bool (defaultArg existingTodo.Completed updateModel.Completed)
            "@id", Sql.int64 existingTodo.Id
      ]
  |> (* etc. *)
```
The main idea is in these expressions:
```fs
defaultArg existingTodo.Name updateModel.Name
defaultArg existingTodo.Completed updateModel.Completed
```
Hope this helps

**Comment by lanyusan** [comment]
Thanks for the quick reply. Your example is mostly what I meant. The only problem is that your example requires knowing the existing or default value in advance.

The problem is that the back end REST handler doesn't know the existing data and shouldn't retrieve existing data from database for such use case.

My approach with Clojure is simple as Clojure is mostly map based and typeless. I build a list of update tuple such as [["name" name] ["completed" completed]] then filter out the tuple with a nil value. 

I am having trouble with finding a simple way to do it with F#. Maybe reflection could help?

**Comment by Zaid-Ajaj** [comment]
@lanyusan I think you can still use `Dictionary<string, obj>` and then write a function that maps `Dictionary<string, obj>` to `UpdateTodoModel` by mapping `obj` to different types when it is not null. So it is possible to get a dynamic approach but I believe doing the approach above would be best.

If you don't have the default values (existing todo), then you could write a more complicated SQL query to use the parameter when it is not null or use the input when it is available

**Comment by lanyusan** [comment]
I did some research and found out with reflection, it could be done with certain type safety.

I am borrowing this code mostly from the book expert F#

```
open System.Reflection

let lookupValue (obj : obj) (nm : string) : 'T =
    obj.GetType().InvokeMember(nm, BindingFlags.GetProperty, null, obj, [||])
    |> unbox<'T>
```
The value for field with type of `Option<'T>` could be matched against `None` and `Some x`. `Some x` can be mapped with x being coerced into certain type to `Some Sql.text / Sql.int ` etc. 

With this, it would be easy to build a function of mapping a   tuple list of ` fieldName * fieldType` to a `fiendName * sqlvalue` then run a filter to eliminate `None` value tuples. The rest is to build sql string and parameters,which would be easy.

Did some quick prototyping in FSI and it seems to work.

**Comment by Zaid-Ajaj** [comment]
If you found a working solution then it's all good and the issue can be closed. I personally don't encourage people to use reflection for their mappings and this library doesn't do any reflection by design but if reflection is working for you, all the better 😄

**Comment by lanyusan** [comment]
Can I ask why you don't recommend reflection? I just started with F#. Would like to learn a little bit more. Thanks.

**Comment by Zaid-Ajaj** [comment]
Well, there are a couple of reasons. Mainly because when you couple types (code) to database tables, that doesn't necessarily make your code "type-safe" because now changes in the code break the application if these changes aren't also reflected the database. This is something that the compiler cannot enforce so although your program compiles and maybe your unit tests will work too, the program will break in production because it relied on types being in sync with the database. 

> I'm not saying reflection is _always_ bad, only prefer not to use it when possible or be very mindful of the points of failure. 

Another reason not to use reflection is to be able to easily map table columns to other types, for example reading a `jsonb` column into string first, then converting it to `JToken` (from Newtonsoft.Json library) or reading `timestamp` as `ZonedDateTime` without extra plugins. 

Finally, using this methodology of writing the data access layer makes the code very simple and allows for tools to better work with it: checkout [Npgsql.FSharp.Analyzer](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer) 

Hope this helps, let me know if you have more questions 😄

**Comment by lanyusan** [comment]
Thanks. Would try Analyzer later.
